// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Record struct {
	ID        string
	UserID    string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
	Wins      sql.NullInt64
	Losses    sql.NullInt64
	Draws     sql.NullInt64
}

type User struct {
	ID             string
	Username       string
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
	HashedPassword string
}
